import scrapy


class FranceUrl(scrapy.Spider):
    name = 'redfin'
    start_urls = [
        'https://www.redfin.com/county/2550/TN/Bradley-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2549/TN/Blount-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2559/TN/Cocke-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2562/TN/Cumberland-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2565/TN/DeKalb-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2573/TN/Grainger-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2563/TN/Davidson-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2574/TN/Greene-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2581/TN/Hawkins-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2590/TN/Johnson-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2591/TN/Knox-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2580/TN/Hardin-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2589/TN/Jefferson-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2597/TN/Loudon-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2605/TN/Meigs-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2598/TN/McMinn-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2606/TN/Monroe-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2616/TN/Rhea-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2617/TN/Roane-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2626/TN/Sullivan-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2622/TN/Sevier-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2623/TN/Shelby-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2631/TN/Union-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2627/TN/Sumner-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2621/TN/Sequatchie-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2634/TN/Washington-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2638/TN/Williamson-County/filter/property-type=land,include=sold-3mo/page-2',
        'https://www.redfin.com/county/2562/TN/Cumberland-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2574/TN/Greene-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2591/TN/Knox-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2589/TN/Jefferson-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2597/TN/Loudon-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2617/TN/Roane-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2622/TN/Sevier-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2623/TN/Shelby-County/filter/property-type=land,include=sold-3mo/page-3',
        'https://www.redfin.com/county/2562/TN/Cumberland-County/filter/property-type=land,include=sold-3mo/page-4',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo/page-4',
        'https://www.redfin.com/county/2591/TN/Knox-County/filter/property-type=land,include=sold-3mo/page-4',
        'https://www.redfin.com/county/2622/TN/Sevier-County/filter/property-type=land,include=sold-3mo/page-4',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo/page-5',
        'https://www.redfin.com/county/2591/TN/Knox-County/filter/property-type=land,include=sold-3mo/page-5',
        'https://www.redfin.com/county/2622/TN/Sevier-County/filter/property-type=land,include=sold-3mo/page-5',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo/page-6',
        'https://www.redfin.com/county/2550/TN/Bradley-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2549/TN/Blount-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2556/TN/Chester-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2545/TN/Anderson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2547/TN/Benton-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2554/TN/Carter-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2555/TN/Cheatham-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2558/TN/Clay-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2553/TN/Carroll-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2548/TN/Bledsoe-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2559/TN/Cocke-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2561/TN/Crockett-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2560/TN/Coffee-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2552/TN/Cannon-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2557/TN/Claiborne-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2551/TN/Campbell-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2562/TN/Cumberland-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2564/TN/Decatur-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2569/TN/Fentress-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2567/TN/Dyer-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2568/TN/Fayette-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2570/TN/Franklin-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2565/TN/DeKalb-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2571/TN/Gibson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2566/TN/Dickson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2575/TN/Grundy-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2572/TN/Giles-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2579/TN/Hardeman-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2578/TN/Hancock-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2573/TN/Grainger-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2563/TN/Davidson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2582/TN/Haywood-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2546/TN/Bedford-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2576/TN/Hamblen-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2583/TN/Henderson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2574/TN/Greene-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2584/TN/Henry-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2577/TN/Hamilton-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2581/TN/Hawkins-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2587/TN/Humphreys-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2585/TN/Hickman-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2590/TN/Johnson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2593/TN/Lauderdale-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2591/TN/Knox-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2594/TN/Lawrence-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2592/TN/Lake-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2586/TN/Houston-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2595/TN/Lewis-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2588/TN/Jackson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2580/TN/Hardin-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2596/TN/Lincoln-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2600/TN/Macon-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2589/TN/Jefferson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2597/TN/Loudon-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2601/TN/Madison-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2605/TN/Meigs-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2598/TN/McMinn-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2604/TN/Maury-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2602/TN/Marion-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2613/TN/Pickett-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2611/TN/Overton-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2609/TN/Morgan-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2603/TN/Marshall-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2610/TN/Obion-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2612/TN/Perry-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2606/TN/Monroe-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2599/TN/McNairy-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2607/TN/Montgomery-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2615/TN/Putnam-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2608/TN/Moore-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2616/TN/Rhea-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2617/TN/Roane-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2619/TN/Rutherford-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2620/TN/Scott-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2625/TN/Stewart-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2618/TN/Robertson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2629/TN/Trousdale-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2626/TN/Sullivan-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2624/TN/Smith-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2622/TN/Sevier-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2628/TN/Tipton-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2623/TN/Shelby-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2631/TN/Union-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2627/TN/Sumner-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2614/TN/Polk-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2632/TN/Van-Buren-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2633/TN/Warren-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2630/TN/Unicoi-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2621/TN/Sequatchie-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2637/TN/White-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2636/TN/Weakley-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2634/TN/Washington-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2638/TN/Williamson-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2635/TN/Wayne-County/filter/property-type=land,include=sold-3mo',
        'https://www.redfin.com/county/2639/TN/Wilson-County/filter/property-type=land,include=sold-3mo',

    ]

    # products-list .product-name font
    def parse(self, response):
        for url in response.css('div.HomeCardContainer'):
            yield {
                'page': response,
                'urls': url.css('div.bottomV2 a::attr("href")').get(),
                'ad': url.css('div.link-and-anchor::text').get(),
                'pr': url.css('span.homecardV2Price::text').get(),
                'sz': url.css('div.HomeStatsV2 .stats:last-child::text').get(),
                'soldate': url.css('div.HomeSash::text').get(),

                #'Type': url.css('div.message::text').get(),
                ##'Sold Date': url.xpath('//span[@class="ehTgwE"]/text()').get(),
                #'Price': url.css('div.Price__Component-rui__x3geed-0::text').get(),
                ##'Price': url.xpath('//span[@data-test="property-card-price"]/text()').get(),
                #'Size': url.xpath('//span[@data-testid="screen-reader-value"]/text()').get(),
                ##'LandSize': url.css('ul.StyledPropertyCardHomeDetailsList-c11n-8-84-3__sc-1xvdaej-0 li b::text').get(),
                ##'Addd1': url.xpath('//div/a[@class="jnnxAW"]/address/text()').get(),
                #'Addd2': url.xpath('//div[@data-testid="card-address-2"]/text()').get(),
                #'Address': url.css('h1.LDPHomeFactsstyles__H1-sc-11rfkby-3::text').get(),
                ## 'urls':url.xpath('//h2/a/text()').get(),
            }

        #next_page = response.css('a.StyledButton-c11n-8-84-3__sc-wpcbcc-0::attr("href")').get()
        #if next_page is not None:
         #   yield response.follow(next_page, self.parse)
